### ISSUE TITLE
Question on copyTo function in propertytree.h (line 420)

### ISSUE THREAD

**Issue by chaoyonghan** [bazza2jw/open62541Cpp#1]
Hi bazza2jw,

This is an awesome project for open62541 users. Thanks a lot for your great work. I'm reading through your code and found one thing I don't understand in propertytree.h.

At line 420, you have n->addChild(n); which I do not understand. If I understand it correctly, you did a deep copy of the node tree in this function. Should it be n->addChild(c); or I understand it wrong? 

Btw, I'm new to github and don't know whether this is a the proper way to issue a code review.

Thanks a lot!

**Comment by bazza2jw** [comment]
Thank you - you are correct. I will update. Maybe the function need removing as it is not used.
