### ISSUE TITLE
clean up refrences for c make build

### ISSUE THREAD

**Issue by michaelanis14** [bazza2jw/open62541Cpp#4]
when trying to use cmake on windows I receive this error :  "Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers."
When further investigate i found alto of hard coded references to libraries files on your computer with your user files.
also no need to push the build folder !

**Comment by hicklin** [comment]
Did you check if the air_monitors brach gives the same issue? The build directory and local references should all have been removed.

**Comment by michaelanis14** [comment]
Just check air_monitors branch, is it clean thanks.
