### ISSUE TITLE
Wrong return value in writeAttribute

### ISSUE THREAD

**Issue by TeunScheffel** [bazza2jw/open62541Cpp#8]
Hi,
I found a small 'slip of the pen':

In open62541server.h, in writeAttribute() the return value is wrong because of _lastError being compared to UA_STATUSCODE_GOOD. The line should be:
                _lastError =  __UA_Server_write(_server, nodeId, attributeId, attr_type, attr);
And then all is fine. Found this when using the writeEnable() on a node.

Best regards,
Teun

**Comment by bazza2jw** [comment]
Thanks. Sorry for the delay.

Bazza
